eup_fit4h/ruby/ vom Lehrer/rails_app/config/routes.rb
Rails.application.routes.draw do
  
  root "events#index"
  
  resources :events do
    resources :registrations
    collection do
      get "showall"
    end
  end

end

eup_fit4h/ruby/ vom Lehrer/rails_app/app/models/event.rb
class Event < ActiveRecord::Base
	has_many :registrations, dependent: :destroy
	validates :name, presence: true
	validates :description, :length => { minimum: 25 }
	validates :capacity, numericality: { only_integer: true, greater_than: 0}
	validates :image_file, allow_blank: true, 
		format: { with: /\w+\.(gif|jpg|png)\z/i, message: "Dateiformat muss jpg, gif, png sein" }
	
	def free?
		self.price.blank? || self.price.zero? 
	end

	def self.upcoming
		where("start_at >= ?", Time.now).order("start_at")
	end
end

eup_fit4h/ruby/ vom Lehrer/rails_app/app/models/registration.rb
class Registration < ActiveRecord::Base
  belongs_to :event
  HOW_HEARD_OPTIONS = ['Newsletter', 'Twitter', 'Web Search', 'Other']

  validates :how_heard, inclusion: { in: HOW_HEARD_OPTIONS }

end

eup_fit4h/ruby/ vom Lehrer/rails_app/app/controllers/events_controller.rb
class EventsController < ApplicationController

	def index
		@events = Event.upcoming 
	end
	def showall
		@events = Event.all
	end
	def show
		@event = Event.find(params[:id])
	end

	def new
		@event = Event.new
	end
	def create
		@event = Event.new(event_params)
		if @event.save
			flash[:notice] = "gut gespeichert ist halb gewonnen."
			redirect_to event_path(@event.id)
		else
			render "new"
		end
	end
	def edit
		@event = Event.find(params[:id])
	end
	def update
		@event = Event.find(params[:id])
		if @event.update(event_params)
			redirect_to event_path(@event.id)
		else
			render "edit"
		end
	end
	def destroy
		@event = Event.find(params[:id])
		@event.destroy
		redirect_to events_path		
	end
	private
		def event_params
			params.require(:event).permit(:name, :description, :location, :price, :start_at, :image_file, :capacity)
		end
end

eup_fit4h/ruby/ vom Lehrer/rails_app/app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
	def index
		@event = Event.find(params[:event_id])
		@registrations = @event.registrations
	end
end

eup_fit4h/ruby/ vom Lehrer/rails_app/app/helpers/application_helper.rb
module ApplicationHelper
	def format_price(event)
		if event.free? 
			#"<strong>FREE</strong>".html_safe
			content_tag(:strong, "Free")
		else
			number_to_currency(event.price, unit: "€ ") 
		end
	end
	def image_for(event)
		if event.image_file.blank?
			image_tag 'dummy.jpg', size: "100x100"
		else
			image_tag event.image_file
		end
	end
end

eup_fit4h/ruby/ vom Lehrer/rails_app/app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
	<% if @event.errors.any? %>
		<div class="panel">
			<ul>
				<% @event.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="row">
		<div class="medium-2 columns">
			<%= f.label :name %>
		</div>
		<div class="medium-10 columns">
			<%= f.text_field :name %>
		</div>
	</div>
	<div class="row">
		<div class="medium-2 columns">
			<%= f.label :description %>
		</div>
		<div class="medium-10 columns">
			<%= f.text_area :description %>
		</div>
	</div>
	<div class="row">
		<div class="medium-2 columns">
			<%= f.label :location %>
		</div>
		<div class="medium-10 columns">
			<%= f.text_field :location %>
		</div>
	</div>
	<div class="row">
		<div class="medium-2 columns">
			<%= f.label :price %>
		</div>
		<div class="medium-10 columns">
			<%= f.number_field :price %>
		</div>
	</div>
	<div class="row">
		<div class="medium-2 columns">
			<%=f.label :start_at %>
		</div>
		<div class="medium-10 columns">
			<%=f.datetime_select :start_at %>
		</div>
	</div>
	<div class="row">
		<div class="medium-2 columns">
			<%=f.label :image_file %>
		</div>
		<div class="medium-10 columns">
			<%=f.text_field :image_file, placeholder: "gif, jpg,png Dateiname" %>
		</div>
	</div>

	<div class="row">
		<div class="medium-2 columns">
			<%=f.label :capacity %>
		</div>
		<div class="medium-10 columns">
			<%=f.number_field :capacity %>
		</div>
	</div>
	
	<div class="row">
		<div class="medium-2 columns"><%= f.submit %></div>
		<div class="medium-10 columns">&nbsp;</div>
	</div>

<% end %>

eup_fit4h/ruby/ vom Lehrer/rails_app/app/views/events/edit.html.erb
<h1>Event: <%= @event.name %> bearbeiten</h1>

<%= render "form" %>

eup_fit4h/ruby/ vom Lehrer/rails_app/app/views/events/index.html.erb
<h1>Upcoming Events</h1>
<p><%= link_to "Neuen Event erstellen", new_event_path %></p>
<p>Zeige folgende <%= @events.size %> Events an:</p>
	<table width="100%">
		<tr>
			<th>Name</th>
			<th>Ort</th>
			<th>Preis</th>
			<th>wann</th>
			<th>Beschreibung </th>
			<th>Show</th>
			<th>Edit</th>
			<th>Del</th>
		</tr>
		<% @events.each do |event| %>
			<tr>
				<td><%= event.name %></td>
				<td><%= event.location %></td>
				<td><%= format_price(event) %></td>
				<td><%= event.start_at %></td>
				<td>
					<%= truncate(event.description, length: 25, separator: ' ', omission: "") %>
					<%= link_to "...", event_path(event.id) %>
				</td>
				<td><%= link_to "Show", event_path(event.id) %></td>
				<td><%= link_to "Edit", edit_event_path(event.id) %></td>
				<td><%= link_to "Delete", event_path(event.id), method: :delete, data: {confirm: "Sicher????"} %></td>
			</tr>
		<% end %>
	</table>
<p>
	<%= link_to "Alle Events", showall_events_path, type: "button", class: "button success" %> 
</p>

eup_fit4h/ruby/ vom Lehrer/rails_app/app/views/events/new.html.erb
<h1>Neuen Event erstellen</h1>

<%= render "form" %>

eup_fit4h/ruby/ vom Lehrer/rails_app/app/views/events/show.html.erb
<h1><%= @event.name %></h1>

<div class="panel flash">
	<%= flash[:notice] %>
</div>
<div class="panel">
	<div class="row">
		<div class="medium-3 columns">
			<%= image_for(@event) %>
		</div>
		<div class="medium-9 columns">
			<%= @event.description %>
		</div>
	</div>
</div>

<div class="panel">
	<div class="row">
		<div class="medium-2 columns">
			Wann
		</div>
		<div class="medium-10 columns">
			<%= @event.start_at %>
		</div>
	</div>

	<div class="row">
		<div class="medium-2 columns">
			Wo
		</div>
		<div class="medium-10 columns">
			<%= @event.location %>
		</div>
	</div>
	<div class="row">
		<div class="medium-2 columns">
			Preis
		</div>
		<div class="medium-10 columns">
			<%= format_price @event %>
		</div>
	</div>
</div>


<p>
	<%= link_to "Back", events_path %><br />
	<%= link_to "Regisiterierungen", event_registrations_path(@event.id) %>
</p>

eup_fit4h/ruby/ vom Lehrer/rails_app/app/views/events/showall.html.erb
<h1>Alle Events</h1>
<p><%= link_to "Neuen Event erstellen", new_event_path %></p>
<p>Zeige folgende <%= @events.size %> Events an:
	<table width="100%">
		<tr>
			<th>Name</th>
			<th>Ort</th>
			<th>Preis</th>
			<th>wann</th>
			<th>Beschreibung </th>
			<th>Show</th>
			<th>Edit</th>
			<th>Del</th>
		</tr>
		<% @events.each do |event| %>
			<tr>
				<td><%= event.name %></td>
				<td><%= event.location %></td>
				<td><%= format_price(event) %></td>
				<td><%= event.start_at %></td>
				<td>
					<%= truncate(event.description, length: 25, separator: ' ', omission: "") %>
					<%= link_to "...", event_path(event.id) %>
				</td>
				<td><%= link_to "Show", event_path(event.id) %></td>
				<td><%= link_to "Edit", edit_event_path(event.id) %></td>
				<td><%= link_to "Delete", event_path(event.id), method: :delete, data: {confirm: "Sicher????"} %></td>
			</tr>
		<% end %>
	</table>
</p>

eup_fit4h/ruby/ vom Lehrer/rails_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>