eup_fit4h/railsdoku/max/Wurst/config/routes.rb
Rails.application.routes.draw do
 root 'projects#index'
 get 'all' => 'projects#showall'
 get 'all_tasks' => 'tasks#showall'
 resources :projects do
 resources :tasks
 end
 get '*path' => 'projects#dne'
 end

eup_fit4h/railsdoku/max/Wurst/app/models/project.rb
class Project < ActiveRecord::Base
 has_many :tasks, dependent: :destroy
 validates :title , :start_date , presence: { message: 'can not be blank' }
 validates :description , length: { minimum: 25 }
 end

eup_fit4h/railsdoku/max/Wurst/app/models/task.rb
class Task < ActiveRecord::Base
 belongs_to :project
 end

eup_fit4h/railsdoku/max/Wurst/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

eup_fit4h/railsdoku/max/Wurst/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
 def index
 end
 def show
 @project = Project.find(params[:id])
 end
 def showall
 @projects = Project.all
 @i = 1
 end
 def new
 @project = Project.new
 end
 def create
 @project = Project.new(params_project)
 if @project.save
 flash[:notice] = 'project created'
 redirect_to project_path(@project.id)
 else
 render 'new'
 end
 end
 def update
 @project = Project.find(params[:id])
 if @project.update(params_project)
 redirect_to project_path(@project.id)
 else
 render 'edit'
 end
 end
 def edit
 @project = Project.find(params[:id])
 end
 def destroy
 @project = Project.find(params[:id])
 @project.destroy
 redirect_to all_path
 end
 private
 def params_project
 permitted_params = params.require(:project).permit(:title, :description, :start_date)
 end
 end

eup_fit4h/railsdoku/max/Wurst/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
 before_action :set_project
 def index
 @tasks = @project.tasks
 end
 def show
 @task = @project.tasks.find(params[:id])
 end
 def new
 @task = @project.tasks.new
 end
 def create
 @task = @project.tasks.new(task_params)
 if @task.save
 redirect_to project_task_path(@project.id, @task.id), alert: 'tasks created'
 else
 render 'new'
 end
 end
 def update
 @task = @project.tasks.find(params[:id])
 if @task.update(task_params)
 redirect_to project_tasks_path(@project.id)
 else
 render 'edit'
 end
 end
 def edit
 @task = @project.tasks.find(params[:id])
 end
 def destroy
 @task = @project.tasks.find(params[:id])
 @task.destroy
 redirect_to project_tasks_path(@project.id)
 end
 private
 def set_project
 @project = Project.find(params[:project_id])
 end
 def task_params
 params.require(:task).permit(:title , :description , :start_date , :end_date)
 end
 end

eup_fit4h/railsdoku/max/Wurst/app/helpers/application_helper.rb
module ApplicationHelper
end

eup_fit4h/railsdoku/max/Wurst/app/helpers/projects_helper.rb
module ProjectsHelper
end

eup_fit4h/railsdoku/max/Wurst/app/helpers/tasks_helper.rb
module TasksHelper
end

eup_fit4h/railsdoku/max/Wurst/app/views/shared/_errors.html.erb
<% if objekt_errors.errors.any? %>
 <div class='panel'>
 <ul>
 <% objekt_errors.errors.full_messages.each do |error| %>
 <li><%= error %></li>
 <% end %>
 </ul>
 </div>
 <% end %>

eup_fit4h/railsdoku/max/Wurst/app/views/tasks/_form.html.erb
<%= form_for([@project, @task]) do |f| %>
 <% if @task.errors.any? %>
 <div id='error_explanation'>
 <h2> <%= pluralize(@task.errors.count , 'error') %> prohibited this task from being saved: </h2>
 <ul>
 <% @task.errors.full_messages.each do |message| %>
 <li> <%= message %> </li>
 <% end %>
 </ul>
 </div>
 <% end %>
 <div class='field'>
 <%= f.label :title %> <br />
 <%= f.text_field :title %>
 </div>
 <div class='field'>
 <%= f.label :description %> <br />
 <%= f.text_area :description %>
 </div>
 <div class='field'>
 <%= f.label :start_date %> <br />
 <%= f.datetime_select :start_date %>
 </div>
 <div class='field'>
 <%= f.label :end_date %> <br />
 <%= f.datetime_select :end_date %>
 </div>
 <div class='field'>
 <%= f.label :project_id %> <br />
 <%= f.number_field :project_id %>
 </div>
 <div class='actions'>
 <%= f.submit %>
 </div>
 <div class='medium-10 columns'>
 <%= link_to 'back', projects_path , :class => 'button' %>
 </div>
 <% end %>

eup_fit4h/railsdoku/max/Wurst/app/views/tasks/edit.html.erb
<h1> editing task </h1>
 <%= render 'form' %>
 <%= link_to 'show tasks' , project_tasks_path(@project.id) , :class => 'button' %>

eup_fit4h/railsdoku/max/Wurst/app/views/tasks/index.html.erb
<p id='notice'> <%= notice %> </p>
 <h1> tasks </h1>
 <table>
 <thead>
 <tr>
 <th> title </th>
 <th> description </th>
 <th> start date </th>
 <th> end date </th>
 <th> project </th>
 <th colspan='3'></th>
 </tr>
 </thead>
 <tbody>
 <% @tasks.each do |task| %>
 <tr>
 <td> <%= task.title %> </td>
 <td> <%= task.description %> </td>
 <td> <%= task.start_date %> </td>
 <td> <%= task.end_date %> </td>
 <td> <%= task.project_id %> </td>
 <td> <%= link_to 'show' , project_task_path(@project.id , task.id) %> </td>
 <td> <%= link_to 'Edit', edit_project_task_path(@project.id , task.id) %> </td>
 <td> <%= link_to 'Destroy', project_task_path(@project.id , task.id) , method: :delete, data: { confirm: 'Are you sure?' } %> </td>
 </tr>
 <% end %>
 </tbody>
 </table>
 <br />
 <%= link_to 'new task', new_project_task_path , :class => 'button' %>
 <%= link_to 'back' , project_path(@project.id) , :class => 'button' %>

eup_fit4h/railsdoku/max/Wurst/app/views/tasks/new.html.erb
<h1> new task </h1>
 <%= render 'form' %>
 <%= link_to 'back' , project_tasks_path , :class => 'button' %>

eup_fit4h/railsdoku/max/Wurst/app/views/tasks/show.html.erb
<p id='notice'> <%= notice %> </p>
 <p>
 <strong> title: </strong>
 <%= @task.title %>
 </p>
 <p>
 <strong> description: </strong>
 <%= @task.description %>
 </p>
 <p>
 <strong> start date: </strong>
 <%= @task.start_date %>
 </p>
 <p>
 <strong> end date: </strong>
 <%= @task.end_date %>
 </p>
 <p>
 <strong> project: </strong>
 <%= @task.project_id %>
 </p>
 <%= link_to 'back' , project_tasks_path(@project.id) , :class => 'button' %>